# Generated by Django 5.0.2 on 2024-02-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
